# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - sufianfirstazurefunctionapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stg'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'sufianfirstazurefunctionapp'
          slot-name: 'stg'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_20F80F1F8AFC4635B28A2EBC4903CC09 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: Azure App Configuration Sync
        uses: Azure/AppConfiguration-Sync@v1.1.2
        with:
          # Path to the configuration file in the repo, relative to the repo root. Also supports glob patterns and multiple files
          configurationFile: 'appsettings.json'
          # Format of the configuration file. Valid values are: json, yaml, properties
          format: json
          # Connection string for the App Configuration instance
          connectionString: ${{ secrets.AZURE_CONNECTION_STRING }}
          # Separator used when flattening the configuration file to key-value pairs
          separator: ':'
          # Specifies whether to use a strict sync which will make the App Configuration instance exactly match the configuration file (deleting key-values not in the configuration file). Defaults to false
          strict: true # optional
          # Prefix that will be added to the front of the keys
          # prefix: # optional
          # Label to use when setting the key-value pairs. If not specified, a null label will be used
          # label: # optional
          # Max depth (positive number) for flattening the configuration file
          # depth: # optional
          # Stringified form of a JSON object with the following shape: { [propertyName: string]: string; }
          # tags: # optional
          # Content type associated with the values
          # contentType: # optional
